name: medline

channels:
  - conda-forge

dependencies:
  - ipywidgets=7.6.3
  - jsonlines=2.0.0
  - jupyterlab=3.0.13
  - lxml=4.6.3
  - networkx=2.5.1
  - numpy=1.20.2
  - pandas=1.2.3
  - python=3.9.2
  - requests=2.25.1
  - scipy=1.6.2
  - tenacity=7.0.0
  - tqdm=4.60.0
  - pip
  - pip:
    - git+https://github.com/dhimmel/pubmedpy.git@9d716768f5ab798ec448154588e4fd99afd7584a
    - nxontology==0.1.4

